name: Publish Docker image
on:
  push:
    branches:
    - mainee
jobs:
  build:
    strategy:
      matrix:
        include:
        - uplift_version: 2.21.0
          node_version: 16
          full_node_version: v16.20.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sh ./scripts/download.sh files/node-linux-x64-musl.tar.gz https://unofficial-builds.nodejs.org/download/release/${{ matrix.full_node_version }}/node-${{ matrix.full_node_version }}-linux-x64-musl.tar.gz
    - run: sh ./scripts/download.sh files/uplift.tar.gz https://github.com/gembaadvantage/uplift/releases/download/v${{ matrix.uplift_version }}/uplift_${{ matrix.uplift_version }}_linux-x86_64.tar.gz
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          UPLIFT_VERSION=${{ matrix.uplift_version }}
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-dind:16
